apiVersion: kubeflow.org/v1beta1
kind: Profile
metadata:
  name: kubeflow-user-example-com
spec:
  owner:
    kind: User
    name: user@example.com
---
apiVersion: kubeflow.org/v1beta1
kind: Profile
metadata:
  name: profile-test
spec:
  owner:
    kind: User
    name: test@example.com
