kind: Namespace
apiVersion: v1
metadata:
  name: aws-observability
  labels:
    aws-observability: enabled
---
kind: ConfigMap
apiVersion: v1
metadata:
  name: aws-logging
  namespace: aws-observability
data:
  output.conf: |
    [OUTPUT]
      Name  es
      Match *
      Host  search-opensearch-demo-rqhhrcrsm57brgpnxstbzyogpa.us-east-1.es.amazonaws.com
      Port  443
      AWS_Auth On
      AWS_Region us-east-1
      tls On
      Index fargate_log
      Type  _doc
      