apiVersion: apps/v1
kind: Deployment
metadata:
  name: demo-app-deploy
  labels:
    app: demo-app
spec:
  selector:
    matchLabels:
        app: demo-app
  replicas: 3
  strategy:
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: demo-app
    spec:
      containers:
        - name: demo-app
          image: 349361870252.dkr.ecr.us-west-2.amazonaws.com/jenkins-demo:latest
          ports:
            - containerPort: 80
              protocol: TCP
          imagePullPolicy: Always
          
