apiVersion: apps/v1
kind: Deployment
metadata:
  name: deployment-20
spec:
  selector:
    matchLabels:
      app.kubernetes.io/name: app-20
  replicas: 2
  template:
    metadata:
      labels:
        app.kubernetes.io/name: app-20
    spec:
      containers:
      - image: public.ecr.aws/l6m2t8p7/docker-2048:latest
        imagePullPolicy: Always
        name: app-20
        ports:
        - containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: service-20
spec:
  ports:
    - port: 80
      targetPort: 80
      protocol: TCP
  type: NodePort
  selector:
    app.kubernetes.io/name: app-20
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: ingress-20
  annotations:
    alb.ingress.kubernetes.io/group.name: team1
    alb.ingress.kubernetes.io/scheme: internet-facing
    alb.ingress.kubernetes.io/target-type: ip
    alb.ingress.kubernetes.io/conditions.service-20: >
      [{"field":"http-header","httpHeaderConfig":{"httpHeaderName": "HeaderName", "values":["app1"]}}]
spec:
  ingressClassName: alb
  rules:
    - http:
        paths:
        - path: /
          pathType: Prefix
          backend:
            service:
              name: service-20
              port:
                number: 80
