apiVersion: v1
kind: Secret
metadata:
  name: aws-secret
  namespace: argo-events
type: Opaque
data:
  accesskey: QUtJQVZDVjRYQ1dXS1I2RlU0RjI=
  secretkey: aFJJZFhEY244NFphZGNmRUZDbTJSTC9YbDBwNXV2cmo0L2NPNjNsKw==
