apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: secretsmanager-es
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: secretsmanager-store
    kind: SecretStore
  target:
    name: internal-secret
    creationPolicy: Owner
  data:
  - secretKey: internal-testkey
    remoteRef:
      key: safran-dev-demo #AWS Secrets Manager secret name
      property: testkey #AWS Secrets Manager secret key