apiVersion: scheduling.k8s.io/v1
kind: PriorityClass
metadata:
  name: app-high-priority
value: 1000000
preemptionPolicy: Never #  cannot preempt other pods
description: "This priority class should be used for XYZ service pods only."