apiVersion: apps/v1
kind: Deployment
metadata:
  name: app1
  labels:
    app: web-server
spec:
  replicas: 3
  selector:
    matchLabels:
      app: web-server
  template:
    metadata:
      labels:
        app: web-server
    spec:
      containers:
      - name: web-app
        image: nginx:1.16-alpine
