apiVersion: v1    
kind: Secret
metadata:
     name: mlpipeline-minio-artifact
     namespace: kubeflow
type: Opaque
data:
    accesskey: QUtJQVZDVjRYQ1dXT003SjJMVjU=
    secretkey: Tm4rOXZWazhPR1dOTGNySW1EQmtlNk93QUtvYWdMMDYrZTVuRy8rSw==